# -*- coding: utf-8 -*-
"""FinalYear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOVLVJ8WXEBhF1W32m2QpNh2RGcjO9hz

Clearly Defining the Problem. Having a precise problem definition helps you stay focused on your project, much like a roadmap. ...
Collecting Data. ...
Data Cleaning and Preprocessing. ...
Feature Engineering. ...
Model Selection. ...
Model Training and Evaluation. ...
Model Deployment and Monitoring.
"""

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk

nltk.download('stopwords')
nltk.download('punkt')

movies = pd.read_csv('/content/drive/MyDrive/MOVIE_DATASET/TMDB_all_movies.csv')

movies.head()

movies.info()

movies.isnull().sum()

movies[['title','overview','genres','cast','director']].isnull().sum()

movies.dropna(inplace = True)

required_columns = [
    'title',
    'overview',
    'genres',
    'cast',
    'director',
    'poster_path',
    'vote_average',
    'vote_count'
]

movies = movies[required_columns]

movies['tag'] = (
    movies['overview'].fillna('') + ' ' +
    movies['genres'].fillna('') + ' ' +
    movies['cast'].fillna('') + ' ' +
    movies['director'].fillna('')
)

movies.shape

movies.dropna(inplace =True)
movies.shape

movies.isnull().sum()

movies = movies.sort_values(by="vote_count", ascending=False)
movies = movies.head(10000)

movies.reset_index(drop=True, inplace=True)

movies.info()

movies.head()

tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
vec = tfidf.fit_transform(movies['tag'])
sem = cosine_similarity(vec)

def recommend(movie_title, top_n=5):

    if movie_title not in movies['title'].values:
        return []

    index = movies[movies['title'] == movie_title].index[0]

    distances = list(enumerate(sem[index]))
    distances = sorted(distances, key=lambda x: x[1], reverse=True)

    recommendations = []

    for i in distances[1:top_n+1]:
        recommendations.append({
            "title": movies.iloc[i[0]].title,
            "poster_path": movies.iloc[i[0]].poster_path,
            "rating": movies.iloc[i[0]].vote_average
        })

    return recommendations

recommend('The Dark Knight')

genre_counts = movies['genres'].value_counts()

print(genre_counts.head(20))

recommend('Interstellar')

recommend('Avatar')